### PR TITLE
port to python 38

### PR DESCRIPTION
**Pull request by bissenbay**
Related-To: https://github.com/thoth-station/thoth-application/issues/545

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
lgtm , thanks :100:

**Comment by bissenbay** [comment]
@fridex @pacospace @harshad16 Do I need to add `.aicoe-ci.yaml`?

**Comment by harshad16** [comment]
can you add the following contecnt to `.aicoe-ci.yaml`
```
 
check:
  - thoth-build
  - thoth-precommit
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
  build-stratergy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: slo-reporter
  registry-secret: thoth-station-thoth-pusher-secret
deploy:
  project-org: "thoth-station"
  project-name: "thoth-application"
  image-name: "slo-reporter"
  overlay-contextpath: "slo-reporter/overlays/test/imagestreamtag.yaml"
```

**Comment by bissenbay** [comment]
> can you add the following contecnt to `.aicoe-ci.yaml`
> 
> ```
>  
> check:
>   - thoth-build
>   - thoth-precommit
> build:
>   base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
>   build-stratergy: Source
>   registry: quay.io
>   registry-org: thoth-station
>   registry-project: slo-reporter
>   registry-secret: thoth-station-thoth-pusher-secret
> deploy:
>   project-org: "thoth-station"
>   project-name: "thoth-application"
>   image-name: "slo-reporter"
>   overlay-contextpath: "slo-reporter/overlays/test/imagestreamtag.yaml"
> ```

thanks @harshad16 , https://github.com/thoth-station/slo-reporter/pull/162/commits/cc05330207ced8330f78174272674c16f9d9da60

**Review by pacospace — APPROVED** [review]
Thanks!!

**Pull request merged**
