### PR TITLE
Add build analysis in the report sent by email

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/metrics-exporter/issues/581

## This introduces a breaking change

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
/lgtm

**Comment by harshad16** [comment]
@pacospace  the test will not run as prow is down today. would like this pr to be merged ? 
you can merge the pr manually :+1:

**Comment by pacospace** [comment]
> @pacospace the test will not run as prow is down today. would like this pr to be merged ?
> you can merge the pr manually

Thanks @harshad16, no rush we just need a new release before friday :)

**Review by harshad16 — APPROVED** [review]

**Pull request merged**
